/*
 * ========================================
 *  博客文章数据库 —— 所有文章都在这里添加
 * ========================================
 *
 * 【文章结构模板】
 * {
 *   id: 数字,            // 文章唯一ID（按发布时间递增，最早=1，不要重复）
 *   title: "文章标题",
 *   date: "YYYY-MM-DD",  // 发布日期
 *   category: "分类名",   // 对应分类页的分类：前端开发 / 后端开发 / 数据库 / 人工智能 / 生活随笔 / 学习笔记
 *   summary: "一句话摘要", // 显示在首页卡片上
 *   content: [           // 正文（2~4个小节即可）
 *     { heading: "小节标题", body: "段落正文..." },
 *     { heading: "小节标题", body: "段落正文..." },
 *     { heading: "小节标题", body: "段落正文..." }
 *   ]
 * }
 *
 * ★ 新增文章请在下方数组末尾（]; 之上）追加，id 按现有最大值 +1
 * ========================================
 */
var uniBlogData = [
	{ id: 1, title: "Git 工作流最佳实践", date: "2026-06-02", category: "学习笔记", summary: "总结 Git Flow、GitHub Flow 和 Trunk-Based 三种工作流的优缺点与适用场景。", content: [ { heading: "一、Git Flow", body: "Git Flow 是最经典的分支模型，包含 master（正式发布）、develop（开发主线）、feature（功能开发）、release（发布准备）、hotfix（紧急修复）五类分支。适合有固定发布周期的传统项目，但分支繁多、合并复杂，对于持续交付团队来说过于笨重。" }, { heading: "二、GitHub Flow", body: "GitHub Flow 极度简化：只有 master 和 feature 分支。任何新功能从 master 拉分支开发，完成后提交 Pull Request 进行代码审查，审查通过后合并到 master 并立即部署。适合持续部署的 SaaS 项目，配合完善的自动化测试和 CI/CD 流水线。" }, { heading: "三、Trunk-Based Development", body: "主干开发要求开发者频繁（至少每天）将代码合并到主干，分支存活不超过一天。通过 Feature Flag 控制未完成功能的可见性，Branch by Abstraction 处理大型重构。这是 Google、Facebook 等大厂采用的工作流，对自动化测试和代码审查要求极高。" } ] },
	{ id: 2, title: "Webpack 5 模块联邦", date: "2026-06-05", category: "前端开发", summary: "探索 Webpack 5 Module Federation 微前端方案，实现多团队协作下的模块共享。", content: [ { heading: "一、微前端概念与挑战", body: "微前端将前端应用拆分为独立开发、测试、部署的微应用，由主应用统一编排。挑战包括：技术栈异构集成、应用间通信、样式隔离、公共依赖去重。Module Federation 是 Webpack 5 原生支持的解决方案，相比 iframe 和 qiankun 更加轻量和高效。" }, { heading: "二、Module Federation 配置", body: "通过 ModuleFederationPlugin 配置 exposes（暴露模块）和 remotes（消费远程模块）。name 定义容器唯一标识，filename 指定远程入口文件名，shared 声明共享依赖（如 React、Vue）以避免重复加载。运行时通过动态 import 加载远程模块，实现按需加载和懒加载。" }, { heading: "三、实战与注意事项", body: "搭建示例：主应用通过 remotes 消费子应用暴露的组件，子应用独立运行和部署。注意共享依赖的版本兼容性，使用 singleton 选项确保单例。调试时需处理跨域问题，生产环境建议子应用与主应用同域部署。Module Federation 2.0 增加了更好的类型支持和运行时 API。" } ] },
	{ id: 3, title: "算法学习：动态规划专题", date: "2026-06-08", category: "学习笔记", summary: "系统梳理动态规划解题思路，通过背包问题、最长公共子序列等经典题目加深理解。", content: [ { heading: "一、DP 的核心思想", body: "动态规划（DP）的核心是将原问题分解为重叠子问题，通过记忆化（自顶向下）或表格递推（自底向上）避免重复计算。适用条件：最优子结构（大问题的最优解包含子问题的最优解）和无后效性（过去状态不影响未来决策）。确定状态定义和状态转移方程是解题关键。" }, { heading: "二、背包问题系列", body: "0-1 背包：每件物品只能选一次，状态转移 dp[i][w] = max(dp[i-1][w], dp[i-1][w-wi] + vi)。完全背包：每件物品无限次，内层循环正序遍历容量。多重背包是 0-1 背包的扩展，可通过二进制优化或单调队列优化。背包问题本质上是在约束条件下求最优组合。" }, { heading: "三、最长公共子序列（LCS）", body: "LCS 是经典的双序列 DP 问题。状态定义：dp[i][j] 表示 s1 前 i 个字符与 s2 前 j 个字符的 LCS 长度。转移方程：字符相同时 dp[i][j]=dp[i-1][j-1]+1，不同时取 max(dp[i-1][j], dp[i][j-1])。LCS 的变体包括最长公共子串（要求连续）和编辑距离。" } ] },
	{ id: 4, title: "夏日露营记", date: "2026-06-10", category: "生活随笔", summary: "记录第一次野外露营的经历，从装备准备到星空下的感悟，分享新手避坑指南。", content: [ { heading: "一、露营装备清单", body: "第一次露营，按清单准备了帐篷、睡袋、防潮垫、露营灯、折叠桌椅和便携炉具。看似简单的物品打包起来却装满了一整个后备箱。老司机建议：新手先买帐篷和睡袋，其余可逐步添置，避免一次投入过大又未必用得上。" }, { heading: "二、营地搭建初体验", body: "到达露营地已是下午三点，选了一块平坦的高地开始搭帐篷。看似简单的帐篷，对着说明书折腾了半小时才勉强立起来。内帐、外帐、地钉、风绳，每一步都有讲究。营友提醒晚上风大，又加了四根风绳加固，这个决定在后半夜证明非常明智。" }, { heading: "三、星空与篝火", body: "夜幕降临后，远离城市光污染的星空璀璨得让人说不出话。银河横跨天际，偶尔有流星划过。围着篝火煮茶聊天，手机信号微弱反而让人彻底放松。这次露营最大的收获是：偶尔切断与数字世界的连接，回归自然的节奏，是对身心最好的疗愈。" } ] },
	{ id: 5, title: "机器学习特征工程实践", date: "2026-06-12", category: "人工智能", summary: "介绍特征工程核心方法，包括数据清洗、特征编码、特征选择与降维技术。", content: [ { heading: "一、数据清洗", body: "真实数据充满缺失值、异常值和噪声。缺失值处理可采用删除、均值或中位数填充、模型预测填充等策略，需根据缺失比例和业务含义选择。异常值检测使用 IQR（箱线图）或 Z-Score 方法，处理时需谨慎，因为异常值可能包含重要信息。" }, { heading: "二、特征编码方法", body: "类别特征编码是将文本类别转换为数值。One-Hot 编码适合无序类别但维度高，Label Encoding 适合有序类别但会引入虚假顺序。目标编码（Target Encoding）使用目标变量的统计量替代类别，信息量大但有泄露风险，需配合交叉验证使用。" }, { heading: "三、特征选择与降维", body: "特征选择方法包括：过滤法（卡方检验、互信息、相关系数）、包裹法（递归特征消除 RFE）和嵌入法（L1 正则化、树模型特征重要性）。PCA 是最常用的线性降维方法，保留方差最大的主成分。t-SNE 适合高维数据可视化，但不能用于特征转换。" } ] },
	{ id: 6, title: "PostgreSQL 窗口函数详解", date: "2026-06-15", category: "数据库", summary: "深入讲解窗口函数语法与应用，包括 ROW_NUMBER、RANK、LAG/LEAD 等。", content: [ { heading: "一、窗口函数基础", body: "窗口函数在查询结果的窗口（一组行）上执行计算，不减少结果行数。OVER 子句定义窗口范围，PARTITION BY 分组，ORDER BY 定义窗口内排序。与 GROUP BY 不同，窗口函数保留每行的独立性，适合排名、累计、移动平均等分析需求。" }, { heading: "二、排名函数实战", body: "ROW_NUMBER() 为每行分配唯一序号，RANK() 相同值排名相同但跳过后续排名，DENSE_RANK() 相同值排名相同且不跳过。NTILE(N) 将数据均匀分为 N 个桶。实际应用：分页查询的替代方案、成绩排名、数据均匀分组采样等。" }, { heading: "三、LAG 与 LEAD 的应用", body: "LAG(column, N) 访问当前行向前第 N 行的数据，LEAD(column, N) 则访问向后第 N 行。典型场景包括计算环比增长率、相邻时间段差值、连续登录天数分析。配合 CASE WHEN 可识别数据变化点，实现状态转换追踪。" } ] },
	{ id: 7, title: "Docker 容器化部署实战", date: "2026-06-18", category: "后端开发", summary: "从 Dockerfile 编写到 docker-compose 编排，完整演示 Node.js 应用容器化部署。", content: [ { heading: "一、Dockerfile 编写要点", body: "选择合适的基础镜像（alpine 版本更小巧），多阶段构建分离构建环境和运行环境，减小最终镜像体积。合理利用镜像层缓存，将不常变化的依赖安装放在前面。使用 .dockerignore 排除 node_modules 等文件，避免将敏感信息打包进镜像。" }, { heading: "二、docker-compose 编排", body: "docker-compose.yml 定义多容器应用的服务、网络和卷。Node.js 应用加 Redis 加 MySQL 三个服务通过自定义网络通信，depends_on 控制启动顺序。环境变量通过 .env 文件管理，卷挂载实现热重载开发，healthcheck 确保依赖服务就绪后再启动应用。" }, { heading: "三、生产环境部署", body: "镜像推送到 Docker Hub 或私有 Registry 后，在生产服务器拉取运行。使用 Nginx 作为反向代理处理 SSL 终止和静态资源。配合 Docker Swarm 或 Kubernetes 实现服务编排、滚动更新和自动扩缩容。日志收集用 ELK 栈，监控告警用 Prometheus 加 Grafana。" } ] },
	{ id: 8, title: "Redis 缓存策略实践", date: "2026-06-20", category: "后端开发", summary: "介绍 Redis 常用缓存策略，包括缓存穿透、击穿、雪崩的成因与解决方案。", content: [ { heading: "一、缓存穿透的应对", body: "缓存穿透指查询不存在的数据，请求穿过缓存直接打到数据库。解决方案：布隆过滤器预先过滤不存在的 key，或将空值也缓存（设置较短过期时间）。接口层增加参数校验，过滤非法请求。终极方案是使用布隆过滤器加空值缓存双保险。" }, { heading: "二、缓存击穿的防护", body: "缓存击穿是热点 key 过期瞬间大量并发请求直接打到数据库。解决方案：互斥锁（setnx）保证只有一个请求能重建缓存，逻辑过期方案让旧数据在重建期间继续服务。永不过期加后台异步更新是最稳健的方案，适用于对实时性要求不高的场景。" }, { heading: "三、缓存雪崩的预防", body: "缓存雪崩指大量 key 同时过期或 Redis 宕机，导致数据库瞬时压力过大。预防措施：为过期时间添加随机值分散过期时刻，构建 Redis 哨兵集群实现高可用，结合本地缓存作为二级缓存，以及限流降级保护数据库。" } ] },
	{ id: 9, title: "TypeScript 高级类型技巧", date: "2026-06-22", category: "前端开发", summary: "掌握泛型、条件类型、映射类型等高级特性，写出更安全的类型定义代码。", content: [ { heading: "一、泛型的进阶用法", body: "泛型不仅用于函数和类，还可用于类型别名和接口。泛型约束（extends）限制类型参数的范围，泛型默认值简化调用。结合 keyof 操作符获取对象键的联合类型，实现类型安全的属性访问器。泛型工具类型如 Partial、Required、Pick 大幅提升类型复用性。" }, { heading: "二、条件类型", body: "条件类型（T extends U ? X : Y）根据类型关系进行分支选择，相当于类型的 if/else 语句。infer 关键字在条件类型中提取类型变量，例如提取函数返回类型 ReturnType、提取 Promise 解析类型 Awaited。递归条件类型可处理嵌套结构。" }, { heading: "三、映射类型与模板字面量", body: "映射类型（[K in keyof T]）遍历对象属性并转换类型，如将所有属性变为可选或只读。as 子句可重新映射键名，配合模板字面量类型可实现精确的字符串处理，如将属性名统一添加前缀或后缀，构建类型安全的事件系统。" } ] },
	{ id: 10, title: "CSS Grid 布局完全指南", date: "2026-06-25", category: "前端开发", summary: "系统学习 CSS Grid 布局，包含网格容器属性、常见布局模式与响应式设计技巧。", content: [ { heading: "一、Grid 基础概念", body: "CSS Grid 是二维布局系统，同时控制行和列。通过 display: grid 声明网格容器，grid-template-columns 和 grid-template-rows 定义轨道。fr 单位按比例分配剩余空间，minmax() 约束尺寸范围，repeat() 简化重复轨道定义，这些工具组合可灵活构建各种布局。" }, { heading: "二、网格项目的放置", body: "通过 grid-column 和 grid-row 可精确控制项目的位置和跨度，使用命名的网格线或 span 关键字。grid-template-areas 提供可视化布局方式，用字符串描述整个页面结构。auto-fill 和 auto-fit 结合 minmax 实现无需媒体查询的响应式网格。" }, { heading: "三、实战布局案例", body: "经典的三栏布局：grid-template-columns: 200px 1fr 300px。卡片网格：grid-template-columns: repeat(auto-fill, minmax(280px, 1fr))。居中盒子：place-items: center。Grid 与 Flexbox 配合使用效果更佳，宏观用 Grid 划分区域，微观用 Flexbox 对齐内容。" } ] },
	{ id: 11, title: "读书笔记：《代码整洁之道》", date: "2026-06-28", category: "学习笔记", summary: "Robert C. Martin 经典著作的阅读心得，总结命名规范、函数设计、注释原则等要点。", content: [ { heading: "一、有意义的命名", body: "变量名应当名副其实，让读者一望而知其用途。避免使用单字母或缩写（循环变量除外），使用能读出来的名称，使用可搜索的名称。类名用名词，方法名用动词，每个概念对应一个词，避免同义词混用造成混淆。" }, { heading: "二、函数的艺术", body: "函数应当短小精悍，只做一件事并做好。参数越少越好，超过三个应考虑封装为对象。避免使用布尔参数表示函数行为分歧，这暗示函数做了不止一件事。使用异常代替返回错误码，让错误处理逻辑与主流程分离。" }, { heading: "三、注释的真相", body: "最好的注释是不需要注释的代码，用清晰的命名和结构让代码自解释。注释容易过时，过时的注释比没有注释更危险。必要的注释包括：法律信息、复杂算法的意图说明、TODO 标记、以及公共 API 的文档。" } ] },
	{ id: 12, title: "周末骑行日记：城市绿道探索", date: "2026-07-01", category: "生活随笔", summary: "记录周末沿城市绿道骑行的所见所感，分享沿途风景与骑行路线推荐。", content: [ { heading: "一、出发前的准备", body: "周六清晨六点，检查了单车胎压和刹车，带上水壶和能量棒就出发了。选择的路线是沿河绿道，全长约 35 公里，预计骑行三小时。清晨的阳光温柔地洒在路面上，微风拂面，城市的喧嚣尚未苏醒，这正是骑行的最佳时刻。" }, { heading: "二、沿途风景与见闻", body: "绿道两旁种满了银杏和梧桐，盛夏的绿荫形成天然遮阳棚。路过湿地公园时，看到了白鹭在浅滩觅食，还有晨练的老人在打太极。骑行至河湾处，视野豁然开朗，宽阔的河面倒映着蓝天白云，让人忍不住停下来拍照留念。" }, { heading: "三、骑行感悟", body: "三个半小时的骑行虽然有些疲惫，但精神却格外清爽。远离屏幕和代码，用双脚丈量城市的另一面，是对身体和心灵的双重充电。推荐这条路线给同样热爱骑行的朋友，建议清晨出发，避开正午烈日，记得做好防晒。" } ] },
	{ id: 13, title: "Transformer 架构解析", date: "2026-07-03", category: "人工智能", summary: "详解自注意力机制、多头注意力和位置编码，理解大语言模型的底层原理。", content: [ { heading: "一、自注意力机制", body: "自注意力允许模型在处理每个词时，关注输入序列中的所有词并计算相关性权重。通过 Query、Key、Value 三个矩阵的乘法运算，生成上下文感知的表示。相比 RNN 的串行处理，自注意力可并行计算，极大提升训练效率，同时捕获长距离依赖关系。" }, { heading: "二、多头注意力", body: "多头注意力将输入投影到多个不同的子空间，每个头独立计算自注意力，最后拼接并线性变换。多个头能关注不同位置和不同语义维度的信息，使模型同时从多个角度理解输入。实验表明 8-16 个头效果较佳，头数过多会稀释每个头的表示能力。" }, { heading: "三、位置编码与训练", body: "Transformer 本身不具备序列顺序感知能力，需要通过位置编码注入位置信息。原始论文使用正弦/余弦函数生成固定位置编码，后续模型也探索了可学习的位置嵌入。训练时使用 Teacher Forcing 策略和交叉熵损失，通过大量的文本语料预训练获得通用语言理解能力。" } ] },
	{ id: 14, title: "深度学习：从感知机到神经网络", date: "2026-07-05", category: "人工智能", summary: "用通俗的语言讲解深度学习基本概念，手把手带你从感知机推导到多层神经网络。", content: [ { heading: "一、感知机模型", body: "感知机是最简单的人工神经网络单元，接收多个输入信号，通过加权求和与阈值判断输出 0 或 1。其本质是线性分类器，只能解决线性可分问题。单层感知机无法处理异或（XOR）问题，这直接推动了多层神经网络的发展。" }, { heading: "二、激活函数的作用", body: "激活函数为神经网络引入非线性能力，使其能逼近任意复杂函数。Sigmoid 将输出映射到 (0,1)，适合二分类但易饱和导致梯度消失。ReLU 计算简单、收敛快，是目前最常用的激活函数。Softmax 将输出转化为概率分布，用于多分类任务。" }, { heading: "三、从浅层到深层", body: "通过堆叠多个隐藏层，深层神经网络能逐层提取更抽象的特征表示。前向传播计算预测值，反向传播利用链式法则计算梯度并更新参数。批标准化加速训练，Dropout 防止过拟合，Adam 优化器自动调整学习率，这些技术使深层网络训练成为可能。" } ] },
	{ id: 15, title: "MongoDB 聚合管道入门", date: "2026-07-08", category: "数据库", summary: "从零开始学习 MongoDB 聚合管道，掌握重点操作符与实战案例。", content: [ { heading: "一、聚合管道概念", body: "MongoDB 聚合管道是将文档依次通过多个处理阶段，每个阶段对文档进行转换后传递给下一阶段。管道操作不修改原始数据，输入输出均可独立控制。相比 Map-Reduce，聚合管道的性能更优、语法更简洁，支持丰富的内置操作符。" }, { heading: "二、常用操作符详解", body: "match 用于过滤文档，建议放在管道前端以减少后续处理量。group 按指定字段分组并执行累加计算，支持 sum、avg、max 等累加器。project 控制输出字段，可添加计算字段和条件表达式。sort、limit、skip 用于排序和分页。" }, { heading: "三、实战案例", body: "以电商订单数据为例，通过聚合管道实现按商品分类统计销售额：先 match 筛选已完成订单，再 group 按分类聚合求和，最后 sort 降序排列。配合 lookup 实现多表关联查询，unwind 展开数组字段，可完成复杂的多维数据分析需求。" } ] },
	{ id: 16, title: "MySQL 索引优化实战", date: "2026-07-10", category: "数据库", summary: "深入分析 B+Tree 索引原理，结合真实案例讲解索引设计、SQL 调优与慢查询排查。", content: [ { heading: "一、B+Tree 索引原理", body: "MySQL InnoDB 引擎使用 B+Tree 作为索引结构，所有数据按主键顺序存储在叶子节点，非叶子节点只存储键值用于导航。非主键索引（二级索引）的叶子节点存储的是主键值，查询需要回表操作，这也是覆盖索引优化的核心原理。" }, { heading: "二、索引设计原则", body: "遵循最左前缀原则，联合索引中范围查询会中断后续列的索引使用。高选择性的列优先建索引，避免在索引列上使用函数或表达式。频繁更新的列不适合建过多索引，注意联合索引与单列索引的冗余关系，使用 EXPLAIN 分析执行计划。" }, { heading: "三、慢查询排查与优化", body: "开启 slow_query_log 记录执行时间超过阈值的 SQL。使用 pt-query-digest 工具分析慢查询日志，找出高频低效的 SQL。常见优化手段包括：改写子查询为 JOIN、合理分页避免大 OFFSET、覆盖索引减少回表、以及适当使用查询缓存和应用层缓存。" } ] },
	{ id: 17, title: "Python Flask 搭建 RESTful API", date: "2026-07-12", category: "后端开发", summary: "使用 Flask 框架快速构建 RESTful API，涵盖路由设计、请求验证与数据库集成。", content: [ { heading: "一、Flask 框架简介", body: "Flask 是 Python 最流行的轻量级 Web 框架之一，核心极简但扩展性极强。通过装饰器定义路由，Jinja2 模板引擎渲染页面，丰富的第三方扩展支持 ORM、表单验证、认证授权等功能，非常适合快速构建 API 服务。" }, { heading: "二、路由与请求处理", body: "使用 @app.route() 装饰器定义 RESTful 端点，通过 methods 参数限制 HTTP 方法。request 对象获取 JSON、表单和查询参数，jsonify 返回 JSON 响应。使用 Blueprint 组织大型应用的路由结构，结合 marshmallow 库实现请求参数序列化与校验。" }, { heading: "三、数据库集成", body: "Flask-SQLAlchemy 是最常用的 ORM 扩展，提供声明式模型定义和查询接口。通过 db.Model 定义表结构，db.session 管理事务。使用 Flask-Migrate 管理数据库迁移，Alembic 自动生成迁移脚本，确保开发和生产环境数据库版本一致。" } ] },
	{ id: 18, title: "Node.js 性能优化指南", date: "2026-07-15", category: "后端开发", summary: "探讨 Node.js 应用性能瓶颈排查与优化方案，包含内存管理、异步流程控制与集群模式。", content: [ { heading: "一、性能瓶颈分析", body: "Node.js 应用常见的性能瓶颈包括 CPU 密集型计算阻塞事件循环、内存泄漏导致 GC 频繁、数据库查询低效、以及不合理的异步流程设计。使用 clinic、0x 等工具生成火焰图，配合 Chrome DevTools 进行 CPU Profiling 和 Memory Profiling，可快速定位问题。" }, { heading: "二、内存管理最佳实践", body: "Node.js 默认堆内存上限约 1.4GB（64位），可通过 --max-old-space-size 调整。避免在闭包中持有大对象引用，及时清理定时器和事件监听器，使用 WeakMap 和 WeakSet 防止内存泄漏。Stream 模式处理大文件比 Buffer 更省内存。" }, { heading: "三、Cluster 集群模式", body: "Node.js 单进程只能利用一个 CPU 核心，cluster 模块可创建多个工作进程共享同一端口，充分利用多核 CPU。主进程负责分发连接，工作进程处理请求。配合 PM2 进程管理工具，可实现零停机重启、负载均衡和进程守护。" } ] },
	{ id: 19, title: "Vue 3 Composition API 实战", date: "2026-07-18", category: "前端开发", summary: "从 Options API 迁移到 Composition API 的最佳实践，涵盖 ref、reactive、computed 等核心 API。", content: [ { heading: "一、为什么选择 Composition API", body: "Options API 按选项（data、methods、computed）组织代码，当组件功能复杂时，同一逻辑分散在不同选项中，难以维护。Composition API 允许按功能组织代码，将相关逻辑聚合在一起，更利于逻辑复用和 TypeScript 类型推导。" }, { heading: "二、ref 与 reactive 的区别", body: "ref 用于包装基本类型值，通过 .value 访问和修改，在模板中会自动解包。reactive 用于创建响应式对象，直接访问属性即可。ref 也可以包装对象类型，内部会调用 reactive。选择建议：基本类型用 ref，对象类型根据是否需要整体替换来决定，通常 reactive 更方便。" }, { heading: "三、组合式函数的最佳实践", body: "组合式函数（Composables）是 Composition API 的核心复用模式，以 use 开头命名。将可复用的有状态逻辑封装为函数，返回响应式数据和方法。保持单一职责，避免副作用，确保在不同组件中独立运行，是编写高质量组合式函数的关键。" } ] },
	{ id: 20, title: "JavaScript 异步编程详解", date: "2026-07-20", category: "前端开发", summary: "深入理解 Promise、async/await 与事件循环机制，掌握现代 JavaScript 异步编程的核心概念与最佳实践。", content: [ { heading: "一、同步与异步的概念", body: "JavaScript 是单线程语言，这意味着同一时间只能执行一个任务。同步代码按顺序执行，前一个任务完成后才会执行下一个；而异步代码则允许任务在后台执行，不阻塞主线程，等结果就绪后再通过回调、Promise 等方式通知调用方。理解同步与异步的区别，是掌握 JavaScript 编程的基础。" }, { heading: "二、Promise 核心用法", body: "Promise 是 ES6 引入的异步编程方案，它代表一个尚未完成但未来会完成的操作。通过 .then() 链式调用处理成功结果，.catch() 捕获异常，.finally() 执行清理逻辑。Promise.all、Promise.race、Promise.allSettled 等静态方法可应对不同的并发场景，使代码相比回调地狱更加清晰可维护。" }, { heading: "三、async/await 实战技巧", body: "async/await 是 Promise 的语法糖，让异步代码看起来像同步代码。async 函数始终返回 Promise，await 会暂停函数执行直到 Promise 完成。配合 try/catch 可优雅处理错误，结合 for...of 可顺序执行异步操作。需要注意的是 await 会阻塞当前 async 函数内部的后续代码，但不影响外部执行。" } ] },

	/* ========================================
	 * ★★★ 新文章写在这里（]; 之前）★★★
	 * 从这行开始追加，格式如上，id 自增（当前最大 id=23）
	 * ======================================== */
	{ id: 21, title: "CSS 实现毛玻璃效果", date: "2026-07-22", category: "前端开发", summary: "使用 backdrop-filter 和半透明背景，一行代码打造流行的毛玻璃质感。", content: [
		{ heading: "一、核心属性", body: "毛玻璃效果的核心是 backdrop-filter: blur() 属性，它会对元素后面的内容应用模糊滤镜。配合半透明背景色（如 rgba(255,255,255,0.3)），就能在保持内容可读的同时透出背景的模糊色彩。" },
		{ heading: "二、兼容性处理", body: "backdrop-filter 在现代浏览器中已得到广泛支持，但在旧版浏览器中可能需要降级方案。建议使用 @supports 特性检测，不支持时回退到纯色半透明背景，确保基础视觉效果不受影响。" }
	] },
	{ id: 22, title: "Markdown 写作小技巧", date: "2026-07-23", category: "学习笔记", summary: "三个提升 Markdown 写作效率和美观度的实用技巧。", content: [
		{ heading: "一、表格对齐", body: "Markdown 表格通过冒号控制对齐：左侧冒号左对齐，右侧冒号右对齐，两侧都有则居中。合理使用对齐能让数据更易读，配合代码块和引用可以构建结构清晰的文档。" },
		{ heading: "二、折叠块", body: "在支持 HTML 的 Markdown 渲染器中，可以使用 details 和 summary 标签创建折叠块，用来收纳长篇代码或补充说明，保持正文简洁。" }
	] },
	{ id: 23, title: "三分钟了解 WebSocket", date: "2026-07-24", category: "后端开发", summary: "快速认识 WebSocket——让浏览器和服务器双向实时通信的技术。", content: [
		{ heading: "一、HTTP 的局限", body: "传统 HTTP 是请求-响应模式，客户端不发请求服务器就无法推送数据。早期的轮询方案（定时发请求）既低效又浪费资源，长轮询虽然有所改进，但本质上仍是一问一答。" },
		{ heading: "二、WebSocket 握手", body: "WebSocket 通过一次 HTTP 升级握手建立持久连接，之后双方可以在任意时刻互相发送消息，无需等待对方请求。Socket.IO 等库在浏览器不支持时自动降级为长轮询，保证兼容性。" }
	] },
	{ id: 24, title: "新建分类试验", date: "2026-07-29", category: "自定义分类实例", summary:"文章简介试验字句。", content: [
		{ heading: "一、标题一", body: "部分一内容实例",},
		{ heading: "二、标题二", body: "部分二内容实例"}
	] }
];
